[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "habitflow"
version = "1.0.0"
authors = [
    { name="Rajnish Singh" }
]
description = "A privacy-first interactive terminal habit tracker with ANSI contribution heatmaps."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS :: MacOS X",
]

[project.urls]
"Homepage" = "https://github.com/rajnishsingh/HabitFlow"

[project.scripts]
habitflow = "habitflow.habitflow:main"
